### ISSUE TITLE
Improve documentation - ONLY Production accounts

### ISSUE THREAD

**Issue by bdeanindy** [grokify/smsbot-ringcentral-lita#10]
Sandbox accounts should NOT be used with this application due to adverse effects related to some upcoming feature releases by RingCentral.

This should be addressed in the documentation accordingly.

**Comment by grokify** [comment]
This is technically due to the handlers loaded which listen for specific routes and that those routes may be incompatible with messages sent from RingCentral sandbox accounts which have a test disclaimer prefix.

I'll look to include a handler that will work for sandbox accounts.

**Comment by grokify** [comment]
The demo has been updated to support RingCentral developer sandbox accounts by updating to [lita-inspirebot](https://github.com/grokify/lita-inspirebot) v0.0.3

The `README.md` has also been updated to indicate RingCentral developer sandbox accounts require handlers that support the sandbox SMS prefix.
