### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by bdeanindy** [grokify/smsbot-ringcentral-lita#2]
- [ ] Provide link to Developer Portal
- [ ] Add `Prerequisites` Header/Section
- [ ] In `Prerequisites` section: Include required Ruby version for any local development (current required version is 2.2.2)
- [ ] Address the Zendesk environment variables #1
- [ ] What is the `SMS number created and available`? Is this a RingCentral Extension within an account which has `SMS` enabled (if this is accurate, provide link to documentation for developers to be able to locate if SMS is enabled in their RingCentral account, or whom to contact to determine this account feature setting)
- [ ] SMS is not supported by RingCentral accounts where SMS is enabled. Address this in the documentation accordingly.

**Comment by bdeanindy** [comment]
@grokify if you could answer #1 then I will be able to submit a complete PR for these documentation issues sir.

**Comment by grokify** [comment]
Merged
