### ISSUE TITLE
PubNub Upgrade Notice during `bundle install`

### ISSUE THREAD

**Issue by bdeanindy** [grokify/smsbot-ringcentral-lita#3]
While initializing this repository locally, I received the following:

UPGRADE NOTICE: Pubnub 3.8.0 and higher versions are using Celluloid instead of EventMachine for asynchronous processing.

Is there a sub-dependency which needs updated, or is this expected behavior?

**Comment by grokify** [comment]
This is an expected behavior and informational behavior for the [PubNub dependency](https://github.com/pubnub/ruby).
