### ISSUE TITLE
Fix typo in Markdown of README.md

### ISSUE THREAD

**Issue by bdeanindy** [grokify/smsbot-ringcentral-lita#9]
There is a typo in the markdown in the following sentence:

> Lita configuration is loaded in lita_config.rb and [lita_dotenv]().lita_dotenvenables loading of many configuration types via the environment (.env` file or system / Heroku env).

Lita configuration is loaded in [lita_config.rb](lita_config.rb) and [lita_dotenv](.lita_dotenv) enables loading of many configuration types via the environment variables depending upon if you're using `.env` to load environment variables or if you are using Heroku environment variables.

**Comment by grokify** [comment]
Fixed
